/**
 * Generated by smali2java 1.0.0.558
 * Copyright (C) 2013 Hensence.com
 */

package com.charming.weather.entity.news;

import java.io.Serializable;

public class Root implements Serializable {
    private int error_code;
    private String reason;
    private Result result;

    public void setReason(String reason) {
        reason = reason;
    }

    public String getReason() {
        return reason;
    }

    public void setResult(Result result) {
        result = result;
    }

    public Result getResult() {
        return result;
    }

    public void setError_code(int error_code) {
        error_code = error_code;
    }

    public int getError_code() {
        return error_code;
    }
}
